### ISSUE TITLE
More Dependabot problems

### ISSUE THREAD

**Issue by John-Robbins** [John-Robbins/tbp#33]
Still can't find the pyproject.toml.

Also add GitHub Actions checking, too.

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions once a week
      interval: "weekly"
    groups:
      action-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "Dependa"
```
