### ISSUE TITLE
Matrix Job Results:NOPE! Matrix jobs don't properly report success or failure.

### ISSUE THREAD

**Issue by John-Robbins** [John-Robbins/tbp#41]
Good gracious! The dumb never stops. In my [CI.yml](https://github.com/John-Robbins/tbp/blob/b97b7a25963bf201d4609d8aa40d6afb47bf61b5/.github/workflows/CI.yml) I have the `Tests & Coverage` job, which is a matrix job defined as follows:

```
test-cov-job:
    needs: [fight-github-job, lint-types-job]
    name: "Tests & Coverage"
    # Only run on changed code files.
    if: ${{needs.fight-github-job.outputs.code == 'true'}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]
```

In my Protected Branch settings, I have `Tests & Coverage` as a required status check:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/c756f285-ded2-435b-8848-9e2308296769">

Silly me assumed that when one defines a matrix job, the status of the entire job would be the result of all the matrix sub jobs. Nope! There's no status at all passed back to protected branch. Any PR, that requires `Tests & Coverage` will not pass, even though **ALL THREE SUB JOBS RAN SUCCESSFULLY!**

<img width="700" alt="image" src="https://github.com/user-attachments/assets/0d8c1418-da9d-4757-a31c-c050a6fe13e7">

You enter, but never leave (the PR successfully anyway):

<img width="700" alt="image" src="https://github.com/user-attachments/assets/e766ca88-7240-4ba0-8c7d-21034aa40fa5">

This has been a bug for over [4 years](https://github.com/orgs/community/discussions/26822).

At least we have something of a [workaround](https://github.com/orgs/community/discussions/26822#discussioncomment-5122101), which is to add another job that needs the matrix job and checks the results.

I'll have to implement that solution.
